services:
  api:
    build: .
    command: python -m uvicorn app.api:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./app:/app/app
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
    restart: always
    env_file:
      - ./db_config.env

  postgres-db:
    image: postgres:latest
    env_file:
      - ./db_config.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pg-admin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"

volumes:
  postgres-data: